//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCountServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordCountServiceReference.IWordCountService")]
    public interface IWordCountService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCountService/CountingWordsInFileMultThrd", ReplyAction="http://tempuri.org/IWordCountService/CountingWordsInFileMultThrdResponse")]
        System.Collections.Generic.Dictionary<string, int> CountingWordsInFileMultThrd(byte[] fileByteArr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCountService/CountingWordsInFileMultThrd", ReplyAction="http://tempuri.org/IWordCountService/CountingWordsInFileMultThrdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> CountingWordsInFileMultThrdAsync(byte[] fileByteArr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCountService/TestConnection", ReplyAction="http://tempuri.org/IWordCountService/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordCountService/TestConnection", ReplyAction="http://tempuri.org/IWordCountService/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWordCountServiceChannel : WordCountServiceReference.IWordCountService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WordCountServiceClient : System.ServiceModel.ClientBase<WordCountServiceReference.IWordCountService>, WordCountServiceReference.IWordCountService
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WordCountServiceClient() : 
                base(WordCountServiceClient.GetDefaultBinding(), WordCountServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWordCountService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WordCountServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WordCountServiceClient.GetBindingForEndpoint(endpointConfiguration), WordCountServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WordCountServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WordCountServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WordCountServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WordCountServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WordCountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.Dictionary<string, int> CountingWordsInFileMultThrd(byte[] fileByteArr)
        {
            return base.Channel.CountingWordsInFileMultThrd(fileByteArr);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> CountingWordsInFileMultThrdAsync(byte[] fileByteArr)
        {
            return base.Channel.CountingWordsInFileMultThrdAsync(fileByteArr);
        }
        
        public string TestConnection()
        {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync()
        {
            return base.Channel.TestConnectionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWordCountService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWordCountService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/WordCountService/WordCountService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WordCountServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWordCountService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WordCountServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWordCountService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWordCountService,
        }
    }
}
